### ISSUE TITLE
Eliminate unnamed hard-wired constants in code

### ISSUE THREAD

**Issue by tomalin** [cms-tracklet/firmware-hls#110]
CMS coding rules forbid unnamed hard-wired constants in the code. Although we're well behaved here, a couple of dozen have survived. Please eliminate these. (P.S. I've not checked IR or VMR yet, since they are soon to be updated).

## LayerRouter

•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/LayerRouter.h#L9
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/LayerRouter.cpp#L8
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/LayerRouter.cpp#L19
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/LayerRouter.cpp#L21
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/LayerRouter.cpp#L37

## Match Calculator

•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/MatchCalculator.h#L266
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/MatchCalculator.h#L267
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/MatchCalculator.h#L286
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/MatchCalculatorTop.cc#L17

## Match Engine

•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/MatchEngine.cc#L171
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/MatchEngine.cc#L175
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/MatchEngine.h#L90

## MemoryBinned

•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/MemoryBinned.v#L32

## Projection Router

•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/ProjectionRouter.h#L175
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/ProjectionRouter.h#L180
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/ProjectionRouter.h#L187

## Tracklet Calculator

•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L80
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L339
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L341
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L347
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L370
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L383
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L387
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L394
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletCalculator.h#L470

## Tracklet Engine

•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletEngine.h#L160
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletEngine.h#L162
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletEngine.h#L169
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletEngineTop.cc#L6
•       https://github.com/cms-tracklet/firmware-hls/blob/937145cf43bccc84825bd5c2ea60ce087cfcae02/TrackletAlgorithm/TrackletEngineTop.cc#L16

**Comment by pwittich** [comment]
@djcranshaw @aehart @aperloff please take a look and tag others.

**Comment by pwittich** [comment]
#111 closes this issue

**Comment by aehart** [comment]
@pwittich Is LayerRouter obsolete, and if so, is there any reason not to go ahead and remove it in #111.

**Comment by pwittich** [comment]
#111 is merged
