### ISSUE TITLE
Unused FM memories in MC

### ISSUE THREAD

**Issue by aehart** [cms-tracklet/firmware-hls#120]
@bryates I wanted to make note of this issue here so that we don't forget about it.

The current top function for the MC, which represents MC_L3PHIC, has ports for eight FM memories, while it is connected to only two in the wires file. We should use template parameters to "inform" HLS of this, so that it only generates ports for the two FM memories in use.

An example of how this might be done can be found in the TC, where bit masks are defined in TrackletCalculator_parameters.h that are then used to select which TPROJ memories are valid and can be written to in TrackletCalculator.h.

**Comment by bryates** [comment]
This has been addressed in PR #123
