### ISSUE TITLE
Arrays of memories

### ISSUE THREAD

**Issue by aehart** [cms-tracklet/firmware-hls#40]
A while ago, we discussed the issue of having arrays of memories as inputs/outputs to the processing modules. The TrackletCalculator, e.g., currently takes in the all-stubs and stub-pair memories as arrays. However, @zctao pointed out the potential issue of having to copy memories into arrays in the big function that calls all the modules.

I think we can get around this by simply declaring the memories in arrays to begin with in this big function. For example, instead of declaring the memories as
```c++
StubPairMemory SP_L1PHIC12_L2PHIB10;
StubPairMemory SP_L1PHIC12_L2PHIB11;
StubPairMemory SP_L1PHIC12_L2PHIB12;
…
```
and then passing them individually to the relevant processing modules, we would declare them in an array as
```c++
StubPairMemory SP[N_SP_MEMS];
```
and pass the subarray needed by a given processing module with
```c++
TrackletCalculator_L1L2<…>(…, &SP[23], …);
```
In this example, the block starting at index 23 is passed to `TrackletCalculator_L1L2`.

I tested this approach with the following working example just to make sure HLS didn't throw a fit:
```c++
void
test(const ap_int<16> input[8], ap_int<32> * const output)
{
  *output -= *output;

  ap_int<16> scaled_input[8];
  scaleInput<2, 1>(&input[0 * 2], &scaled_input[0 * 2]);
  scaleInput<2, 2>(&input[1 * 2], &scaled_input[1 * 2]);
  scaleInput<2, 3>(&input[2 * 2], &scaled_input[2 * 2]);
  scaleInput<2, 4>(&input[3 * 2], &scaled_input[3 * 2]);

  sumArray<8>(scaled_input, output);
}

// Scale N array entries by C.
template<uint8_t N, int8_t C> void
scaleInput(const ap_int<16> input[N], ap_int<16> output[N])
{
  for (uint8_t i = 0; i < N; i++)
    output[i] = C * input[i];
}

// Add N array entries.
template<uint8_t N> void
sumArray(const ap_int<16> input[N], ap_int<32> * const output)
{
  for (uint8_t i = 0; i < N; i++)
    *output += input[i];
}
```
This module scales the first two entries of the input array by one, the second two by two, etc., and then adds the entries and stores it in the output. The scaling is done using subarrays. This example gives the expected output in a C test-bench and is successfully synthesized in HLS, so it seems that HLS is OK with this.

This approach only works if we can arrange the inputs/outputs for a processing module as contiguous entries in an array. So, for example, if the TrackletProjection memories were passed as input subarrays to the ProjectionRouter, they could not be passed as output subarrays to the TrackletCalculator because this would require a different ordering. So maybe in general we want to pass subarrays as inputs to processing modules where appropriate, but not necessarily as outputs.

Let me know what you think of this approach. It would simplify the interfaces of some processing modules at the cost of any trace of readability in the big function that calls all the modules. In any case, it seems like passing arrays of memories is at least possible in some cases without having to make copies of the memories.

**Comment by pwittich** [comment]
is this issue still relevant?

**Comment by aehart** [comment]
Probably not anymore. I'll go ahead and close it.
